### ISSUE TITLE
Segment validation

### ISSUE THREAD

**Issue by stephan83** [stratumn/sdk#106]
The goal is to implement the basics of segment validation. We should start simple for now (segment JSON is valid, previous link exists, etc..), but prepare for Blueprint rules.

I think a validator should be able to validate a segment given a `store.Adapter`. In simple terms, it should be able to validate a segment which may require fetching other segments from the store.

I imagine the interface would be somethink like:

```go
// Validator validates a segment.
type Validator interface {
	// Returns an error if the segment isn't valid, <nil> otherwise.
	Validate(store.Adapter, *cs.Segment) error
}
```

We can then define a chain of validators to enable multiple validators. I imagine it could be implemented doing something like this:

```go
type Chain []Validator

// Validate implements github.com/stratumn/sdk/validation/Validator.Validate.
func (c Chain) Validate(a store.Adapter, s *cs.Segment) error {
	for _, v := range c {
		if err := v.Validate(a, s); err != nil {
			return err
		}
	}

	return nil
}
```

However, it becomes trickier for a Tendermint node, because the store adapter being used doesn't contain segments in the mempool which are needed for validation. I believe this could be resolved by implementing a `store.Adapter` that uses another `store.Adapter` and a set of new segments not yet saved to implement its interface.

I think this design would work, and should make it possible to add validation both for Tendermint nodes and when not using Tendermint.

What do you think?

**Comment by such** [comment]
Looks great to me!

**Comment by stephan83** [comment]
We should declare a `store.ReadonlyAdapter` interface to make sure a validator can't create new segments.
