### ISSUE TITLE
cs: standardize evidence / support multi evidence

### ISSUE THREAD

**Issue by stephan83** [stratumn/sdk#112]
Right now tmstore uses a different format than the Bitcoin fossilizer. We need to make it consistent.

Also currently multiple evidences from different sources (ie: tmstore + fossilizer) don't work.

Let's discuss.

**Comment by simonvadee** [comment]
What do you thin of this format for an evidence ?
```
{
  <backend>: [{ proof... }, ... ],
  bitcoin: [ {'chainId': 'bitcoin:test3', tx, merklePath... }, ... ],
  tendermint: [ {'chainId': 'test-chain-xxx', iavlProof, blockHeader... }, ... ]
}
```
I'm not sure about the lists for each backend, do we need to be able to fossilize a segment with multiple transactions/whatever for a same backend ?

**Comment by such** [comment]
I can see how it could be useful to save a segment in two distinct tendermint blockchains.

I think we should be a bit more ambitious on the standardization of a Merkle Proof.

**Comment by such** [comment]
That's not really the way we should think about evidence. What we try to achieve is the capability of independently validating an evidence. You only need to do so if you are not part of a network.

The evidence format should make it possible to validate the presence of the segment on multiple blockchains. The way it is retrieved/stored/enriched is not completely relevant here. The segment can always be completed by different parties.

**Comment by simonvadee** [comment]
https://paper.dropbox.com/doc/Standardize-Evidence-vu8Z83YI5P8axfeGmcerB

This document describes the goals and constraints for implementing standardized evidences and suggest a design that could solve the curren issues. Feedback is welcome!
