### ISSUE TITLE
tmstore: improve segment notification

### ISSUE THREAD

**Issue by such** [stratumn/sdk#117]
### Expected behavior

Segments should maybe be notified only once we're sure they've been actually commited by +2/3 of validators.

### Actual behavior

Segments are notified as soon as the block has been commited.
Even if this should be OK for non byzantine nodes (they should have not commited an improper block), what happens if +2/3 of validators crash on commit for instance? This should be investigated.
Moreover, the way it is implemented now, once the segment is notified its evidence is not yet available. This could maybe be solved once we add a DidAddEvidence channel ala DidSave.

**Comment by such** [comment]
@t-bast it might be worth it to take this remarks into account as well when designing stratumn/sdk#191

**Comment by t-bast** [comment]
Definitely, this is a good idea to do a re-design of all the thins we wanted to improve at once so that we have the big picture !
