### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by stephan83** [stratumn/sdk#151]
* close remaining issues
* create 0.1.0-rc1 branch
* set version to 0.1.0-rc1
* update changelog
* build and publish prerelease
* merge to master
* update brew recipe
* QA over the weekend
* fix issues
* create 0.1.0 branch
* set version to 0.1.0
* set PRERELEASE to false
* update changelog
* build and publish release
* merge to master
* update brew recipe

**Comment by such** [comment]
isn't it done @stephan83 ?

**Comment by stephan83** [comment]
I think you told me you wanted to resolve a bug with the websocket before? Something about loosing the connection when the machine goes to sleep?

**Comment by such** [comment]
I've not been able to reproduce it so I think we're good

*Adrien Montfort*
*VP Engineering*
Stratumn SAS, 1 bis Cité Paradis, 75010 Paris, France
+33 6 85 28 38 46 • <+33%206%2020%2047%2060%2029> adrien@stratumn.com •
stratumn.com
We are hiring <https://stratumn.com/careers> • Read about us
<http://blog.stratumn.com> • Twitter <https://twitter.com/stratumnhq>
