### ISSUE TITLE
cs: check linkHash when validating a segment

### ISSUE THREAD

**Issue by such** [stratumn/sdk#189]
The hash of `segment.link` should be recomputed to check it is the same than `segment.meta.linkHash`

**Comment by such** [comment]
blocked by stratumn/canonicaljson-js#1

**Comment by piedup** [comment]
There is an error when doing dep ensure with gibson042/canonicaljson-go on travis/linux. No errors when doing dep ensure on mac. Will investigate.

**Comment by piedup** [comment]
Seems to be coming from the .gitmodules in gibson042/canonicaljson-go

**Comment by piedup** [comment]
Issue still open on golang/dep: [#1364](https://github.com/golang/dep/issues/1364)

**Comment by piedup** [comment]
Resolved as gibson042/canonicaljson-go accepted to change the .gitmodules file [gibson042/canonicaljson-go/issues/3](https://github.com/gibson042/canonicaljson-go/issues/3)

**Comment by alexppxela** [comment]
Cool!
