### ISSUE TITLE
tmpop: implement a binary tree optimized for Indigo and update TMStore

### ISSUE THREAD

**Issue by such** [stratumn/sdk#191]
We are currently using `merkle.NewIAVLTree`.
It allows us to:
- output a unique `AppHash` that reflects the entire state of the application
- retrieve a Merkle Path from each segment to the `AppHash`
- store `linkHash` in leaves of the tree

The problem is that it's not that easy to re-compute the hash of the leaf only from the LinkHash (especially in another language than go). It makes it hard to verify the whole Merkle Tree of an evidence.

Ideally the linkHash would be used directly as the hash of the tree leaf.

We could also take advantage of this new implementation to abstract the fact that we're using both a `store.Adapter` and a tree in `tmpop.Commit` and `tmpop.Snapshot`.

The structure of a Proof should also be defined.

Proposed interface:
```
type TreeReader interface {
	GetSegment(linkHash *types.Bytes32) (*cs.Segment, proof []byte, error)

	FindSegments(filter *SegmentFilter) (cs.SegmentSlice, error)

	GetMapIDs(filter *MapFilter) ([]string, error)

	GetValue(key []byte) ([]byte, proof []byte, error)

	Size() (size int, error)

	Hash() (hash []byte, error)
}

type TreeStore interface {
	TreeReader
	store.Writer

	NewTreeBatch() TreeBatch
}

type TreeBatch interface {
	TreeReader
	store.Writer

	Write() error
}
```

Another option would be to add the proof return value directly to the store interface. Stores that don't implement a proof would just return a null object. To be discussed.

**Comment by such** [comment]
blocked by stratumn/sdk#112

**Comment by such** [comment]
Here is a relevant insight from @stephan83:

I was thinking about the SDK and Tendermint. Would this be possible in theory?

1) Make links immutable

Remove:

- Store#SaveSegment(segment)
- Store#DeleteSegment(linkHash)

Add:

- Store#CreateLink(link)
- Store#SetMeta(linkHash, meta)

This makes the mutable/immutable parts of a segment explicit. You can only create a link, neither update it nor delete it. On the other hand you can change the segment meta.

As a result, **once you have proof that a segment was added in a block, you have proof that it exists forever**.

2) Change Tendermint Merkle Trees

Right now, the app hash is the root of an AVL Tree containing all the segments currently in the application. The proof of a segment is a path in that tree.

However, by making links immutable and undeletable, we do not need a tree of all segments. Instead, we can store a simpler, lighter merkle tree for every block containing the segments added in that block.

The app hash can become something like hash(prevBlockHash + merkleTreeRoot). The proof of a segment becomes {blockHeight, blockMerkleTreePath}.

3) Notes

I think segment meta should not be dealt at the blockchain level. The blockchain should only save immutable links. TMStore can deal with the mutable meta part. This means that any data that must be propagated to the other nodes must be inside the link.

**Comment by t-bast** [comment]
Definitely, it's exciting I have a lot of things to understand about our current storage :)
I'll dive into the code, your comments and will start drafting something.
