### ISSUE TITLE
store: get/find segment via short hash

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/sdk#203]
### Expected behavior
`getSegment('536f56ab64')`
and
`findSegments({linkHash: '536f56ab64'})`

### Actual behavior
`getSegment('536f56ab64ce19bf484e8911632fcd140e203c6d6b0c7e9db5d8be6c20244ee2')`

Useful for client who needs to enter hash manually to not have to type in the full hash.

**Comment by such** [comment]
duplicate of stratumn/sdk#180

**Comment by jeremie-stratumn** [comment]
closed as duplicate
