### ISSUE TITLE
store: findSegments filters on link.meta.tags AND meta.tags

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/sdk#204]
### Expected behavior
`findSegments({tags: [tag1, tag2]})` should look for tags inside `link.meta.tags` as well as `meta.tags`

### Actual behavior
At the moment tags belong exclusively to `link.meta.tags`.

### Information about the issue
The reason behind this is, we should be able to track a "branch" (eg a collection of segments that follow each other) of a map by simply referring to the root's linkHash. If I can add the root's link hash to the tags, I can then use `findSegments` with tags filtering to find the whole branch very easily. At the moment, it is impossible to add the `linkHash` to `link.meta.tags` for circular reasons. But we could insert it in `meta.tags` via plugin for ex. That way, `findSegments` via tags would look at the segment's tags which would be the union of `link.meta.tags`and `meta.tags`.

**Comment by such** [comment]
@Jeremie-Dayan I can remember we talked about this issue but I don't really remember the conclusion. Is it still relevant?

**Comment by jeremie-stratumn** [comment]
not relevant anymore. I think the conclusion was that I should generate a uuid to identify my assets and not rely on linkHash for that. Doing that allows me to insert it into link.meta.tags from the beginning. Thx
