### ISSUE TITLE
store: implement a bigchaindb store

### ISSUE THREAD

**Issue by such** [stratumn/sdk#217]
- Study the feasibility
- Implement the new store adapter that uses bigchaindb.
- Train the team

https://www.bigchaindb.com/

nb: we are caretaker of the bigchaindb foundation

**Comment by alexppxela** [comment]
https://paper.dropbox.com/doc/BigchainDB-storage-GIKQqTL1Y7BIFRylFg2pB

**Comment by t-bast** [comment]
Apparently BigchainDB is throwing the towel...so no reason to implement it :)
